access_key_id: "1CXR6M1N827JKZRCNE82"
secret_access_key: "R0+lmeQGJMUf6c5ko+TkMDDzgLL+XW9/tXEuaxyy"
smtp_username: "AKIAI3UFAWI62VS5PQ6A"
smtp_password: "Al9Fd+jc8esCYEf5rwNp5IxKUejsQH/ZuHbL5W5qqiUf"
