access_key_id: "1CXR6M1N827JKZRCNE82"
secret_access_key: "R0+lmeQGJMUf6c5ko+TkMDDzgLL+XW9/tXEuaxyy"
smtp_username: "AKIAIF6XIPJSUS5LPY4Q"
smtp_password: "Atao/wStCwCslj5hBstDV/5rglJ+u19LOQPGhlK/jTJN"
