# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  database: tourfilter_boston
  username: chris
  password: chris
  host: 127.0.0.1
  port: 3306

#development:
#  adapter: mysql
#  database: tourfilter_boston
#  username: test
#  password: test
# host: test.cbeerawtyv8a.us-east-1.rds.amazonaws.com
#  port: 3306


test:
  adapter: mysql
  database: tourfilter_boston
  username: chris 
  password: chris
  host: 127.0.0.1
  port: 3306


production:
  adapter: mysql
  database: tourfilter_boston
  username: test
  password: test
  host: test.cbeerawtyv8a.us-east-1.rds.amazonaws.com
  port: 3306


shared_test:
  adapter: mysql
  database: tourfilter_shared
  username: chris
  password: chris
  host: 127.0.0.1
  port: 3306

shared_development:
  adapter: mysql
  database: tourfilter_shared
  username: chris
  password: chris
  host: 127.0.0.1
  port: 3306

#shared_development:
#  adapter: mysql
#  database: tourfilter_shared
#  username: test
#  password: test
#  host: test.cbeerawtyv8a.us-east-1.rds.amazonaws.com
#  port: 3306

shared_production:
  adapter: mysql
  database: tourfilter_shared
  username: test
  password: test
  host: test.cbeerawtyv8a.us-east-1.rds.amazonaws.com
  port: 3306
  
  
  
