LOREM_IPSUM_TEXT = <<-LOREM_IPSUM
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque ligula ut felis. Vivamus quis erat. Aenean auctor. Integer sapien. Cras nec nibh non lorem gravida malesuada. Nunc non augue varius ligula pellentesque laoreet. Donec convallis laoreet sapien. Sed id augue et ligula ornare pretium. Donec nec elit. Sed at purus sed justo mollis consequat. Sed bibendum nisl sed erat. In libero. Maecenas convallis. Nunc euismod orci non lorem.

Vivamus condimentum, libero vel iaculis sagittis, eros urna sagittis est, vel placerat velit velit eget tellus. Sed tincidunt arcu sed metus. Donec auctor neque ut metus. Curabitur at nisl sed arcu laoreet iaculis. Nam vestibulum. Nullam a arcu. Aliquam justo. Nam luctus. Phasellus laoreet sem id leo. Maecenas dapibus arcu et nibh.

Quisque libero massa, tincidunt sed, auctor quis, tristique et, ante. Pellentesque mollis pulvinar ante. Mauris ut urna. Etiam non nisl sit amet sem hendrerit commodo. Pellentesque laoreet tortor at massa. Nulla tempus, libero at consectetur imperdiet, erat nunc condimentum justo, sed condimentum felis odio non turpis. Phasellus malesuada. Etiam urna ipsum, bibendum a, sodales sit amet, dictum quis, tortor. Proin ipsum lectus, gravida vel, elementum ac, tempus vel, mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus euismod urna. Aenean massa lacus, iaculis a, semper eu, ornare sit amet, urna. Nam at nulla ut libero dapibus ullamcorper. Sed rutrum elit et tortor.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed felis nulla, interdum eget, tempor vel, scelerisque vel, dolor. Ut pharetra ipsum ut purus. Suspendisse eu tortor et sem semper hendrerit. Vivamus dui arcu, pretium id, rutrum sit amet, commodo id, elit. Fusce ut magna in libero laoreet consectetur. Etiam eget nisl. Aliquam bibendum leo nec mi. Phasellus erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam felis.

Aliquam metus nisl, varius vitae, accumsan in, lacinia eget, justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce pharetra nunc et sapien. Sed et elit sit amet orci fermentum condimentum. Cras porttitor suscipit sem. Donec mollis rhoncus pede. Integer vestibulum. In a urna. Curabitur augue. Nunc ac mauris. Mauris nec tellus eu ante imperdiet fringilla. Nam nisi. Curabitur velit. Nunc pretium ultricies mauris. Nullam dapibus ligula sit amet nisi. Maecenas eu sem eget nisi bibendum consequat.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur justo enim, pulvinar sit amet, lacinia in, volutpat et, orci. Nullam iaculis dolor ac ante. Aenean rhoncus. Mauris cursus tempus leo. Quisque eu massa. Fusce imperdiet pede at orci. Vestibulum dapibus. Duis sagittis, dolor in cursus vulputate, metus nisl pharetra arcu, ac accumsan lorem enim ac mauris. Quisque placerat nunc eget dui.

Mauris eleifend nisi. Ut dolor magna, tristique sit amet, commodo id, ullamcorper quis, metus. Suspendisse ut est. Integer vitae tortor. Nunc posuere consequat eros. Morbi sodales rhoncus turpis. Ut feugiat lorem ornare tortor. Suspendisse dapibus, nibh nec cursus aliquam, quam lectus eleifend odio, vitae semper nulla nisl tempor arcu. Ut congue pellentesque nunc. Integer sit amet sapien.

Nullam mollis est a metus. Nullam tempus metus interdum nulla. Nulla fringilla, tortor in varius molestie, nisl sem adipiscing justo, quis lobortis massa nulla ut lectus. Aenean bibendum arcu nec mi. Etiam convallis arcu id felis rutrum auctor. Donec egestas justo sit amet nisi. Duis nunc. Etiam feugiat nulla sit amet eros. Quisque lobortis euismod sapien. Morbi scelerisque. Nullam at mauris vel enim varius scelerisque. In hac habitasse platea dictumst. Maecenas euismod commodo tellus. Pellentesque neque enim, semper convallis, mollis sit amet, dapibus eget, lectus. Duis eleifend augue vitae ipsum.

Morbi tristique mollis lacus. Nunc bibendum ipsum. Duis mauris quam, molestie et, iaculis at, malesuada tincidunt, felis. Nam feugiat condimentum mauris. Proin elit nisi, condimentum ac, facilisis vel, accumsan eu, nisl. Ut gravida venenatis lacus. Aenean interdum ante ut libero. Mauris imperdiet purus blandit odio. Pellentesque sollicitudin erat lacinia mauris. Praesent malesuada odio. Vivamus ac mi. Fusce elementum. Morbi mollis metus tempor orci. Sed libero. Sed et diam nec enim mollis semper.

Donec imperdiet lectus vitae sem. Quisque tempor tellus et nisl fringilla dapibus. Nulla laoreet, mi a lobortis hendrerit, diam tellus tristique tellus, id pellentesque felis dolor quis risus. Nunc pulvinar, dui sodales semper consequat, ipsum mauris aliquam tortor, sed ornare ligula elit ac eros. Etiam placerat auctor neque. In pretium hendrerit odio. Nam imperdiet molestie ante. Morbi sagittis sodales tellus. Fusce sagittis justo vitae risus. Nullam pellentesque. Nulla enim magna, posuere ac, rhoncus eu, ullamcorper et, sem. Vestibulum nec sem ac massa tincidunt tristique. Curabitur rhoncus libero quis dolor. Curabitur id tellus.

Donec adipiscing. Aliquam convallis porta elit. Sed laoreet vehicula dolor. Cras pellentesque, risus sit amet euismod laoreet, lacus eros euismod elit, nec scelerisque massa mauris ut eros. Aliquam erat volutpat. Curabitur tempor, tellus dictum tempor dictum, magna enim vehicula tellus, at tempor lorem leo sit amet orci. Suspendisse et justo. In hac habitasse platea dictumst. Donec mattis, justo ac interdum porta, nisl sem iaculis neque, eget ullamcorper tortor arcu eget augue. Nunc dolor nibh, molestie eget, malesuada id, convallis vel, nisl. Nulla tortor tellus, pellentesque id, iaculis non, pharetra id, odio. Duis porta. Sed ac diam. Aenean et nisi. Fusce dignissim, sapien eu eleifend commodo, mauris sem porta lectus, nec faucibus massa purus pulvinar quam.

Praesent quis nulla. Morbi consequat dapibus dolor. Integer nunc nibh, ultrices sit amet, mollis at, ultrices non, elit. Pellentesque ultricies vestibulum nunc. Sed elementum ligula ut tortor porttitor eleifend. Aliquam varius risus quis ligula. Cras viverra dui vitae quam. Integer tristique mi at nisi. Maecenas a diam. In molestie felis eu nulla volutpat vehicula. Maecenas pretium ligula eu quam. In condimentum magna. Nam vulputate scelerisque eros. Integer eleifend tristique leo. Nam mi. Nulla in turpis. Ut tortor. Nunc in lacus.

Morbi tincidunt tristique nulla. Donec nec massa. Vivamus sed massa. Aliquam malesuada ullamcorper nibh. Praesent bibendum eros id risus. Integer mollis massa at nibh. Sed egestas ullamcorper nisl. Donec commodo libero sed nibh. Mauris placerat, purus id eleifend ultrices, erat tellus ultrices diam, at iaculis orci sem ac neque. Aliquam eu nulla eu lorem pellentesque viverra. Curabitur tincidunt posuere lacus. Nulla facilisi. Maecenas eget nunc in libero fermentum fringilla. Aenean fringilla. Maecenas mi urna, interdum a, tristique quis, ullamcorper eget, odio. In hac habitasse platea dictumst. Proin non orci et odio ornare lacinia. Ut gravida fringilla metus.

In hac habitasse platea dictumst. Vivamus consectetur sollicitudin massa. In tempor massa et mi. Donec vel velit sit amet nisi egestas auctor. Nulla nibh quam, tincidunt non, auctor nec, varius non, lorem. Ut vel metus. Aliquam erat volutpat. Aliquam nec tortor id turpis pretium tincidunt. Nunc justo risus, vestibulum vel, dignissim non, tempus vel, mi. Morbi ornare, felis ac gravida convallis, nunc urna porttitor augue, ac adipiscing odio arcu vel libero. Duis non justo. Donec suscipit turpis ut lectus. Morbi felis nisl, consectetur eu, interdum non, porta et, est. Suspendisse potenti. Cras vulputate. Pellentesque nec quam ac arcu mollis elementum. Morbi nisl. Pellentesque ultrices pellentesque lectus. Aliquam erat volutpat. Donec ac tortor.

Aliquam id nisi. Integer tempor. Vivamus viverra mauris sit amet tellus. Suspendisse pede. Suspendisse sapien. Aenean viverra lectus sed enim. Aliquam id tortor. Mauris neque est, blandit in, ultrices a, malesuada quis, lorem. Integer semper, justo ac porttitor hendrerit, erat leo malesuada magna, quis pulvinar ante augue eget augue. Phasellus ac purus. Morbi interdum sodales risus. Nam tincidunt consectetur ligula. Nam vitae leo quis ligula consectetur lobortis. Donec ut elit sit amet ligula facilisis semper. Aliquam odio. Sed tempus tempor quam. Curabitur ut orci. Donec tristique blandit nibh.

Donec enim lacus, fringilla in, elementum eu, commodo ut, est. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce massa. In sed purus vel nibh porta pretium. Vivamus dui. Nulla facilisi. Suspendisse lobortis. Vivamus lectus purus, malesuada at, convallis id, viverra rhoncus, ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis est sapien, auctor ut, aliquet vitae, tincidunt vel, est. Duis accumsan lobortis nulla. Phasellus aliquam tincidunt est. Suspendisse molestie dapibus nisl. Nam nunc urna, bibendum ut, pretium eu, cursus nec, quam. Morbi eget ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur ornare risus nec dui. Curabitur id dolor. Vestibulum leo massa, imperdiet non, laoreet eu, fermentum vitae, massa. Nullam euismod scelerisque nulla.

Nulla facilisi. Aenean vel mi. Donec quis lacus. Sed quis dolor. Vivamus porta, nulla rhoncus gravida vulputate, odio erat gravida lacus, eget consectetur mi nunc eu sapien. Suspendisse et mi. Aliquam aliquet. Aenean quam tellus, fringilla sit amet, consectetur nec, suscipit id, magna. Integer ipsum. Quisque convallis sem aliquet metus.

Curabitur non ligula vitae leo imperdiet aliquet. Sed in enim quis elit luctus pulvinar. Morbi convallis ultricies nibh. Nulla eu velit ut mi posuere imperdiet. Morbi cursus. Suspendisse fringilla. Morbi vitae justo. Duis sem. Ut vehicula placerat urna. Aenean condimentum ultrices arcu. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean iaculis purus id magna. Phasellus enim nisi, adipiscing quis, luctus vel, pellentesque eu, arcu. Integer dictum, turpis a faucibus vehicula, sem mauris faucibus felis, sit amet luctus lorem leo pulvinar lectus. Pellentesque adipiscing, augue lobortis mattis pellentesque, libero nisl hendrerit quam, ac semper diam risus ac ante. Fusce gravida pellentesque ante. Proin imperdiet, metus ut condimentum lobortis, elit lorem pellentesque massa, eget adipiscing justo dolor sed metus.

Ut vitae diam vitae enim vestibulum ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla tristique suscipit odio. Donec laoreet lobortis arcu. Maecenas lorem erat, bibendum id, consectetur eu, mollis ut, lacus. Curabitur sagittis. Cras eget ipsum. Proin tincidunt augue et leo. Fusce ac urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas consectetur, velit nec lacinia aliquam, libero tortor faucibus arcu, at vestibulum pede ante ac tellus. In vehicula. Ut porta scelerisque odio. Curabitur at eros a ante eleifend placerat. Duis metus neque, ultricies consequat, hendrerit a, gravida pulvinar, libero.

Nullam egestas diam et velit. Integer est. Phasellus ante neque, porttitor eu, vehicula quis, tincidunt accumsan, tellus. Fusce at quam in ante faucibus fermentum. Ut tellus enim, lacinia in, iaculis in, vulputate vitae, justo. Maecenas in nunc hendrerit lectus cursus rutrum. Nunc mollis feugiat mauris. Suspendisse tempor blandit velit. Pellentesque et enim non ante tincidunt molestie. Sed nibh metus, placerat eget, dictum eu, rutrum non, felis. Morbi diam. Pellentesque nunc lectus, feugiat cursus, dapibus nec, placerat sit amet, nisl. Vivamus est. Fusce auctor leo sed tortor. Aliquam id mi vel enim euismod hendrerit. Etiam feugiat pede vel felis. Sed commodo massa sed lectus. Vivamus euismod bibendum est.

Aliquam erat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin felis. Nam pellentesque condimentum erat. Donec accumsan pulvinar dui. Proin dolor dolor, mattis eu, dapibus et, interdum laoreet, risus. Nunc urna. Etiam sem. Sed nibh justo, fringilla vitae, molestie suscipit, imperdiet a, nunc. Phasellus hendrerit, lectus non bibendum tincidunt, nisi justo placerat ante, ac posuere pede diam at turpis. Etiam elementum dolor at leo. Phasellus malesuada neque vel libero. Duis mi. Fusce leo.

Praesent risus lorem, fringilla et, fringilla id, congue ac, massa. Donec velit. Integer ac lectus. Integer magna lectus, fringilla ac, commodo nec, euismod nec, nisl. Nunc viverra rutrum ante. Nunc lectus. Ut sollicitudin, orci eget tincidunt sollicitudin, est metus tempor lectus, ac hendrerit quam nibh et tellus. Maecenas congue, sapien id semper lobortis, turpis orci ultricies pede, et aliquam nisi erat vel magna. Nulla feugiat. Aenean eget odio. Sed nunc tellus, aliquam id, iaculis a, pharetra ac, sem. Fusce iaculis. Phasellus pulvinar faucibus odio. Etiam nibh velit, elementum nec, dictum quis, facilisis ac, ipsum. Aenean arcu magna, condimentum iaculis, facilisis ut, tempus at, dolor. Phasellus leo orci, pulvinar id, porttitor eget, hendrerit quis, erat.

Phasellus mollis nunc quis massa. Proin suscipit rhoncus sem. Ut tincidunt facilisis quam. Vivamus in sapien. Sed quis neque non magna accumsan aliquet. Sed id lorem sed quam aliquam tincidunt. Nunc volutpat. Donec tincidunt enim sit amet elit sodales sollicitudin. Etiam porta diam ut purus. Sed non lorem at sapien malesuada tincidunt. Sed eros. Quisque ante magna, lobortis et, malesuada ac, aliquet a, purus. Maecenas placerat odio id elit. Nunc vitae urna.

Mauris lacus. Fusce dictum diam a ipsum. In sem. Vestibulum sapien. Morbi non erat. Proin gravida, justo a feugiat consectetur, purus metus gravida sapien, quis egestas lorem est vitae odio. Sed nec est sed libero rutrum rutrum. Suspendisse viverra quam et purus. Curabitur venenatis aliquam orci. Aenean sit amet sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean mollis dolor id tortor. Fusce dignissim, nisl nec lobortis pretium, ipsum neque vestibulum nulla, ut varius erat erat vitae ipsum. Morbi pretium nisl sed massa. Quisque dolor. Vestibulum rhoncus adipiscing felis. Vivamus id augue sed arcu pharetra varius. Mauris faucibus elementum felis. Phasellus sed pede.

Phasellus auctor. Mauris blandit, nisi nec blandit blandit, eros nunc aliquam turpis, quis placerat eros massa cursus ante. Suspendisse potenti. Donec rutrum. Vivamus porta. Nunc tincidunt urna quis arcu ornare viverra. Proin lobortis, lacus id vulputate hendrerit, nisi nisl porta dolor, sit amet rhoncus risus lorem id sapien. Sed justo libero, congue at, rhoncus vel, gravida in, nisl. Phasellus porta bibendum lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed mollis, mi in mattis volutpat, eros leo semper nisi, quis placerat quam nulla lobortis urna. Duis convallis odio in nunc.

In mi enim, cursus et, sagittis non, consequat at, tellus. Maecenas massa. Suspendisse tempus. Vivamus venenatis arcu non pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin sit amet dolor non odio imperdiet dignissim. Fusce nulla nibh, iaculis et, malesuada in, aliquet in, mauris. Sed consectetur dictum tellus. Donec lobortis molestie ante. Aliquam vitae elit ac justo sollicitudin iaculis. Praesent imperdiet eleifend eros. Vestibulum eleifend eleifend risus. Maecenas felis.

Maecenas a nibh. Curabitur id orci sed turpis commodo euismod. Duis molestie sem et ligula. Praesent facilisis. Morbi massa mauris, aliquam in, viverra id, tincidunt nec, pede. Phasellus dui. Cras viverra odio ac turpis. Fusce sollicitudin tortor id libero. Nulla volutpat pellentesque quam. Maecenas eu elit. In quis orci. Cras lectus justo, luctus a, cursus at, feugiat quis, nisi. Donec rutrum augue sit amet ipsum. Morbi et nisl et neque vestibulum scelerisque. Mauris varius, urna non aliquet tincidunt, odio orci ullamcorper diam, vel sodales diam odio in orci. Vivamus pede leo, molestie at, ornare ut, pretium sed, tellus. Sed mattis, leo et placerat pulvinar, eros metus posuere enim, sed varius neque nisl in tortor. Suspendisse et purus.

Aliquam a sem at nunc bibendum hendrerit. Nullam at quam. Praesent accumsan tellus vitae mi. Vestibulum in nisi. Donec enim. Aenean vitae nibh. Pellentesque turpis. Integer risus metus, accumsan non, mollis in, malesuada eu, justo. Maecenas mattis, nulla nec hendrerit euismod, eros diam sollicitudin massa, eget placerat elit nunc et metus. In hac habitasse platea dictumst. Sed sem. Suspendisse sit amet orci tempus mauris dapibus malesuada. Suspendisse erat. Vivamus accumsan. Proin ligula. Nam pretium, mi vel lacinia rutrum, arcu pede tristique quam, id semper augue dui lobortis libero. Quisque eu magna nec neque ullamcorper pretium. Maecenas viverra posuere velit. In viverra pellentesque mauris. Proin turpis justo, tristique sed, lacinia id, fermentum sed, metus.

Quisque placerat ornare quam. Nulla lectus nulla, ultrices vel, fermentum eget, sodales ut, magna. Donec vel justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla rhoncus imperdiet sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed gravida ligula et ipsum. Pellentesque pharetra venenatis erat. Aenean blandit semper metus. Curabitur pretium purus sed justo adipiscing luctus. Sed quis pede non nulla vestibulum condimentum.

Phasellus vitae sem condimentum risus sollicitudin lacinia. Nunc felis est, viverra sed, accumsan vel, cursus sed, eros. Donec in purus sit amet tellus volutpat sodales. In hac habitasse platea dictumst. Quisque eros orci, vulputate semper, pellentesque a, ullamcorper nec, dolor. Integer nec eros rhoncus urna facilisis adipiscing. Suspendisse potenti. Donec elementum condimentum elit. Nam arcu ante, imperdiet laoreet, euismod id, posuere at, arcu. Donec ultrices, diam ut egestas vulputate, metus dolor interdum tortor, a fermentum augue eros placerat odio. Proin libero felis, aliquet eu, auctor id, tincidunt vel, tortor. Fusce vel mi vel leo feugiat posuere. Nullam commodo. Quisque elementum hendrerit nunc. Curabitur eleifend, dui sit amet malesuada suscipit, ante mi condimentum justo, vitae tristique pede eros sit amet justo. Quisque leo pede, egestas vitae, tempor posuere, ultricies a, felis. Duis nec ipsum at dui aliquam dignissim.

Fusce rhoncus. Pellentesque elementum sodales lectus. Vivamus interdum diam vitae enim. Nulla at erat in nisl adipiscing euismod. Maecenas auctor velit eget augue. Vestibulum ac nulla. Sed nibh enim, placerat et, gravida nec, molestie aliquam, magna. Quisque consequat sagittis est. Pellentesque sed est. Etiam quis nunc.

Mauris nisl nulla, adipiscing id, auctor condimentum, mattis eu, nisl. Duis felis. Nam volutpat, nisi vel sollicitudin condimentum, leo libero dignissim felis, eu dignissim dolor pede vitae eros. Quisque rutrum ornare erat. Nullam blandit lacus non metus. Nullam adipiscing ipsum ac libero. Praesent aliquet, lorem at pharetra aliquet, libero lectus tempor eros, id blandit lorem dolor cursus eros. Cras adipiscing enim non augue. Praesent ut risus ut nisi dignissim aliquet. Mauris felis justo, imperdiet id, imperdiet et, porttitor at, mauris. Nulla facilisi. Aliquam felis. Nunc at velit. Sed varius ornare augue. Donec feugiat rhoncus eros. Morbi cursus sollicitudin augue. Phasellus lacinia, mi a varius tempor, nulla est eleifend velit, non venenatis magna lorem vitae risus. Nunc quis ligula. Phasellus mollis.

Etiam eu lacus. In eget elit. Praesent accumsan mi a arcu. Aliquam diam libero, condimentum non, scelerisque ut, tincidunt id, sem. Pellentesque vel tortor at turpis faucibus bibendum. Nulla turpis libero, gravida fermentum, ultrices eu, porta et, augue. Proin lorem. Sed dui pede, vestibulum at, sodales ut, scelerisque ut, pede. Ut odio nunc, mollis vel, hendrerit eu, suscipit quis, orci. Vestibulum sagittis semper turpis. Curabitur id turpis. Sed sit amet lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin egestas, pede non viverra lobortis, massa purus dignissim orci, id ullamcorper enim ante at quam.

Vivamus placerat faucibus neque. Mauris elit orci, volutpat vel, adipiscing at, blandit a, erat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras vitae velit ac orci venenatis porttitor. Suspendisse malesuada. Nam sagittis dictum purus. Donec ornare nibh quis ante. Vestibulum bibendum mollis nisi. Aenean sed pede. Phasellus sollicitudin lacinia pede. Nullam turpis enim, faucibus sit amet, elementum sed, placerat eget, risus. Phasellus libero massa, gravida vitae, scelerisque sed, tempor eu, ligula. Nullam et arcu. Vestibulum luctus posuere dolor.

Cras imperdiet tortor quis metus. Maecenas pulvinar velit ac justo. Morbi sem metus, condimentum vel, ultrices nec, aliquet hendrerit, eros. Quisque adipiscing. Nullam elementum blandit neque. Nunc vel ante ut felis tempus dictum. Nullam non diam. Praesent posuere lacus non odio. Suspendisse a massa. Ut laoreet. Quisque a felis vitae arcu venenatis ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ultricies porttitor pede. Nullam velit neque, tincidunt id, tristique ut, blandit a, justo.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla facilisi. Nulla turpis mi, pulvinar quis, tincidunt et, elementum at, justo. Vestibulum pharetra mauris non quam. Duis nisl. Donec lacus augue, scelerisque a, blandit id, pellentesque quis, velit. Duis vitae metus. Sed non lorem ac mi semper eleifend. Nulla posuere velit ac odio. Aenean placerat faucibus nisl. Integer aliquet, neque sed commodo luctus, diam augue varius libero, at suscipit ante nulla vel odio. Integer tempor suscipit risus.

Nulla volutpat sodales mauris. Proin dignissim posuere libero. Suspendisse in sem. Curabitur tempor tristique velit. Sed fringilla tincidunt nibh. Suspendisse odio risus, venenatis a, egestas id, ultricies sit amet, sem. Proin sit amet ipsum. Vestibulum id arcu. Suspendisse pharetra. Nam pulvinar consequat dolor. Quisque bibendum facilisis nisi. Quisque eu augue quis sem scelerisque sagittis. Aliquam nec orci vel neque fermentum hendrerit. Ut convallis odio dignissim augue. Nam egestas pede eu lectus. Phasellus mattis tortor ac purus. Pellentesque ac quam nec felis tempor pulvinar. Integer pulvinar odio at quam.

Cras bibendum dapibus neque. Donec porttitor, lacus in ultricies suscipit, nulla purus vestibulum augue, quis molestie orci lacus vel orci. Nam egestas. Duis urna felis, cursus vel, venenatis et, mattis ac, mauris. Nulla id ipsum at metus congue imperdiet. Nullam molestie. Nulla aliquet rhoncus metus. Morbi justo. Nulla facilisi. Ut mattis. Nunc tortor dolor, semper vel, luctus a, gravida sed, justo. Mauris quis eros.

Etiam vitae tellus. Maecenas tempor pretium erat. Nunc felis leo, porta eu, imperdiet vitae, malesuada ut, odio. Mauris semper, nibh eu varius tristique, dui nisl egestas diam, a luctus est purus eget augue. Quisque condimentum pretium velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam nec quam id quam cursus pellentesque. Etiam bibendum, nulla id venenatis vulputate, justo nulla pulvinar justo, ac pharetra justo ipsum sit amet lectus. Cras eget nibh. Mauris mattis mollis leo. Nulla sagittis adipiscing lacus. Aenean vehicula, augue et auctor vehicula, ante ante dapibus odio, vel tempor dui nunc vel est. Sed lorem nulla, accumsan sit amet, malesuada ac, varius eu, mi. Nam posuere mattis velit. Suspendisse a lorem.

Maecenas mi libero, viverra vel, tempor nec, aliquet ut, sapien. Curabitur suscipit diam ac justo. Etiam ut nisi non risus aliquam lobortis. Vestibulum ut arcu. Aenean feugiat tortor mollis lacus aliquam lobortis. Fusce eget velit vitae nisl commodo varius. Donec sagittis aliquet nisi. Donec nulla tortor, hendrerit quis, commodo sed, scelerisque id, sem. In laoreet. Phasellus quam est, euismod non, volutpat et, posuere vel, nunc. Fusce vehicula.

Aenean elit lectus, mollis nec, vulputate eget, blandit quis, libero. Cras ullamcorper nulla vitae massa. Nulla consectetur. Pellentesque faucibus. Phasellus dapibus, risus vel tristique viverra, augue mi volutpat nulla, eget pharetra risus nibh nec nisl. Maecenas et ligula. Pellentesque sed eros. Integer lacus massa, accumsan ullamcorper, tempus eget, rhoncus sed, urna. Sed venenatis, sem at hendrerit aliquet, diam pede feugiat tortor, non molestie ipsum odio non nibh. Vestibulum magna magna, posuere ut, tincidunt et, laoreet quis, purus. Nullam pulvinar, est sit amet vehicula iaculis, sapien odio tempus mauris, at vulputate urna eros a odio. Sed pharetra lacus id turpis. Morbi ante justo, sollicitudin quis, cursus nec, laoreet et, orci. Suspendisse potenti.

Nam magna lorem, interdum vel, accumsan sit amet, feugiat vel, quam. In ac ipsum sagittis nisi faucibus dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ac nibh sit amet metus fringilla vulputate. In in massa. Aliquam erat volutpat. In ac pede. Curabitur venenatis ligula eget magna. Vestibulum rhoncus. Sed commodo. Donec enim nulla, convallis at, molestie nec, tincidunt rhoncus, purus. Quisque velit tellus, tempus eget, aliquam a, elementum non, diam. Nunc venenatis urna eget ligula. Morbi urna tortor, bibendum quis, blandit vitae, dictum quis, orci. Proin eu risus.

Praesent lorem nisl, ultrices volutpat, accumsan vel, ornare non, dui. Nunc in est. Donec sed libero. Aliquam sit amet purus. Etiam molestie metus eu lacus. Donec tincidunt. Cras eget lorem vitae augue rutrum molestie. Donec vulputate mauris vel quam. Integer consequat porta ipsum. Mauris blandit, felis sed imperdiet tempor, nunc nulla tempus odio, eu molestie leo velit eu nisi. Maecenas dolor pede, ornare pretium, lobortis sit amet, sagittis non, ante. Duis semper fringilla nisl. Sed pharetra, lectus eu feugiat iaculis, sapien justo fringilla mi, sed hendrerit diam justo quis mi. Praesent feugiat laoreet sapien. Nullam elementum nibh et tellus. Quisque diam lacus, tempor at, ornare non, mollis at, massa. Phasellus imperdiet convallis eros. Maecenas egestas, lectus et elementum molestie, sem ante luctus nunc, vel iaculis felis urna at metus.

Praesent aliquam, metus eget tristique congue, urna diam iaculis urna, in adipiscing nisl magna aliquam augue. Integer venenatis massa non augue. Aliquam erat volutpat. Mauris aliquet rutrum mi. Pellentesque nec mauris eu leo viverra consectetur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec gravida. Morbi metus ipsum, posuere at, placerat ut, luctus et, velit. Nulla tempus metus sed est. Sed mauris risus, rutrum id, eleifend in, interdum vel, libero. Pellentesque lacus. In scelerisque, ante feugiat vulputate congue, nibh leo molestie libero, sit amet sollicitudin lacus massa eget velit. Mauris vehicula ligula id quam. Nunc aliquet. Nunc ut magna ut nisl tempor viverra. Donec rhoncus orci nec nisi. Vivamus sodales lectus sit amet orci. In sed elit non libero suscipit laoreet. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Maecenas lacus neque, bibendum posuere, consequat eu, tincidunt hendrerit, leo. Morbi et nisi eget urna bibendum mattis. Cras dictum pulvinar sem. Nulla pretium interdum metus. Nam interdum. Nullam leo. Aliquam odio lacus, sagittis nec, tristique ac, interdum id, lectus. Vivamus risus sem, vestibulum sed, congue sed, hendrerit sed, nisi. Curabitur ipsum orci, luctus et, gravida sit amet, luctus non, mauris. In hac habitasse platea dictumst. Morbi nulla justo, ullamcorper vitae, iaculis consequat, condimentum ut, erat. Sed sollicitudin. Integer auctor vehicula nulla.

Integer non arcu. Duis non turpis auctor est rutrum dapibus. Etiam mattis sapien quis quam. Morbi sed pede vitae tellus dignissim auctor. Aenean est justo, bibendum vel, auctor ut, blandit in, augue. Etiam sit amet metus. In tincidunt sodales nisl. Aliquam luctus venenatis justo. Nullam molestie. Curabitur scelerisque venenatis pede. Mauris ut dolor.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam pretium bibendum ante. Cras venenatis. Aenean mollis porttitor dolor. Integer pulvinar, quam vel pellentesque dapibus, eros purus adipiscing turpis, eget pellentesque erat neque eu dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi ultricies. Praesent in sem posuere nisl viverra mollis. Donec vehicula sem. Nunc ac risus eget mi tempor cursus. Aenean ornare lorem lobortis erat. Donec eu lorem. Quisque tempus.

Suspendisse magna velit, rhoncus ac, mattis id, interdum at, leo. In adipiscing sapien sed est ullamcorper sollicitudin. Pellentesque quis nisi. Phasellus vulputate condimentum ligula. Nullam vel quam quis tellus eleifend eleifend. Ut placerat. Ut eu ipsum. Integer volutpat. Nullam et enim vitae dolor semper mollis. Nam ut erat. Nullam pretium tristique elit. Integer interdum odio sed tortor. Duis consequat. Morbi felis mauris, ullamcorper quis, tincidunt sed, pellentesque sit amet, libero. Integer egestas dui a risus. Sed porta. Nam non nulla. Aliquam ultricies molestie odio. In hac habitasse platea dictumst. In mattis, nulla at congue feugiat, lorem nisi scelerisque purus, a rutrum massa leo ut elit.

Morbi sed arcu. Maecenas luctus nisl non nisi. Sed tristique ante non massa. Nam malesuada arcu quis eros. Integer sapien. Proin iaculis. Etiam pulvinar vehicula velit. In diam sapien, rutrum eu, viverra vel, condimentum nec, lacus. Nullam a orci. Fusce nisi. Mauris turpis est, lacinia non, pulvinar in, aliquam quis, nisi. Fusce eros. Mauris suscipit dolor quis mauris.

Sed iaculis metus at libero. Duis nec est. Proin viverra ante a ante. Etiam sollicitudin, arcu a eleifend pellentesque, arcu magna elementum ligula, sit amet eleifend nunc arcu vel nisl. Sed ultricies ultricies est. Duis quis nulla at leo porttitor sodales. Suspendisse felis ipsum, elementum id, sollicitudin eu, blandit ut, massa. Nulla dolor enim, iaculis ac, lacinia a, fringilla nec, turpis. Aliquam erat volutpat. Donec ullamcorper tellus eu dolor. Phasellus justo nulla, tempus at, dictum ac, vehicula quis, neque. Nam blandit, sem eget accumsan molestie, nulla massa porta eros, sit amet aliquet enim diam a lacus. Vestibulum sodales turpis quis nulla. Nam volutpat consequat risus. Etiam mollis placerat lacus. Pellentesque id massa. Mauris eget massa. Aliquam gravida dolor imperdiet arcu. Duis non arcu ac felis pellentesque sagittis. Pellentesque sed dui in velit lobortis condimentum.

Vivamus hendrerit vulputate augue. Nunc vel purus. Etiam ut lorem. Pellentesque sit amet felis. Nulla lectus mi, consequat eget, vehicula in, posuere eget, lectus. Quisque eget dui eget erat tristique tempus. Praesent ornare, orci id consequat malesuada, sapien ipsum elementum justo, eu aliquet eros lacus commodo orci. Donec metus. Sed non pede. Morbi ac nisi. Vestibulum tincidunt lectus sed magna. Donec lacus. Nam ipsum risus, ultrices quis, cursus at, sodales quis, augue.

Integer pretium metus ac ligula. Vivamus diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque molestie mauris sit amet massa. Vestibulum ut nisl eu enim convallis molestie. Suspendisse ac dui. Aenean rutrum quam sit amet dui aliquam aliquet. Aliquam ut dui. Donec aliquam condimentum neque. Praesent diam orci, mollis et, euismod hendrerit, vehicula vel, nulla. Maecenas pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eleifend elementum ligula. Suspendisse tempus magna eu nisi. Etiam dictum, elit et vestibulum tristique, est sapien adipiscing lectus, nec pellentesque enim lectus in tortor. Pellentesque id risus ac pede dictum volutpat. Sed lacus. In elementum augue sit amet leo. Aenean feugiat turpis non est.

Maecenas pretium. Mauris suscipit dui id nulla. In sed augue quis nisi semper porta. Ut tincidunt quam at mauris. Mauris id neque a tortor suscipit pellentesque. Cras nec est non ante scelerisque sollicitudin. Integer purus felis, eleifend egestas, faucibus vel, fermentum lobortis, metus. Donec non metus id ante tristique rutrum. Maecenas pretium, mi sit amet faucibus pretium, magna est imperdiet lacus, at sollicitudin eros leo sit amet velit. Maecenas pede quam, vulputate eu, varius vel, rutrum in, pede.

Maecenas porttitor neque at nulla. Quisque eget sem quis odio interdum tristique. Proin ultricies diam sit amet ipsum. Sed sit amet felis. Proin ultrices. Suspendisse dolor. Nulla mi. Integer lectus. Duis laoreet nisi quis erat. Ut venenatis tincidunt nunc. Pellentesque adipiscing varius elit. Vivamus sagittis feugiat turpis. Aenean elit. Phasellus sed diam. Sed facilisis elementum turpis. Suspendisse enim eros, hendrerit vitae, egestas non, aliquam et, lorem. Vestibulum turpis.

Integer ligula urna, varius ut, volutpat a, suscipit gravida, risus. Integer augue odio, ullamcorper ac, condimentum non, tincidunt et, libero. Nullam egestas, metus eget porttitor tincidunt, orci leo porta libero, ut tincidunt purus mi in leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sapien eros, porttitor in, tempor a, rhoncus et, libero. Vestibulum mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam posuere luctus nisl. Nunc accumsan turpis nec arcu. Nulla ut tortor at justo tempor suscipit. Vestibulum.
LOREM_IPSUM

def lorem_ipsum_range(l1,l2)
  l = l1+rand(l2-l1)
  start = (LOREM_IPSUM_TEXT.size-l)-1
  start = 0 if start<0
  LOREM_IPSUM_TEXT[start..start+l]
end

def lorem_ipsum(l=500,randomize_length=true)
  l = rand(l) if randomize_length
  start = (LOREM_IPSUM_TEXT.size-l)-1
  start = 0 if start<0
  LOREM_IPSUM_TEXT[start..start+l]
end
